### ISSUE TITLE
cannot run RSI : float() argument must be a string or a number, not 'BasicBar'

### ISSUE THREAD

**Issue by matanume** [gbeced/pyalgotrade#163]
After I test SMA , EMA , MACD. I try to add RSI to my code.

`self.my_rsi = rsi.RSI(feed[instrument], 9)`

But this error occur. How could I fix this?

Traceback (most recent call last):
  File ".../venv/lib/python3.9/site-packages/pyalgotrade/dispatcher.py", line 109, in run
    eof, eventsDispatched = self.__dispatch()
  File ".../venv/lib/python3.9/site-packages/pyalgotrade/dispatcher.py", line 97, in __dispatch
    if self.__dispatchSubject(subject, smallestDateTime):
  File ".../venv/lib/python3.9/site-packages/pyalgotrade/dispatcher.py", line 75, in __dispatchSubject
    ret = subject.dispatch() is True
  File ".../venv/lib/python3.9/site-packages/pyalgotrade/feed/__init__.py", line 106, in dispatch
    dateTime, values = self.getNextValuesAndUpdateDS()
  File ".../venv/lib/python3.9/site-packages/pyalgotrade/feed/__init__.py", line 90, in getNextValuesAndUpdateDS
    ds.appendWithDateTime(dateTime, value)
  File ".../venv/lib/python3.9/site-packages/pyalgotrade/dataseries/bards.py", line 64, in appendWithDateTime
    super(BarDataSeries, self).appendWithDateTime(dateTime, bar)
  File ".../venv/lib/python3.9/site-packages/pyalgotrade/dataseries/__init__.py", line 144, in appendWithDateTime
    self.getNewValueEvent().emit(self, dateTime, value)
  File ".../venv/lib/python3.9/site-packages/pyalgotrade/observer.py", line 65, in emit
    handler(*args, **kwargs)
  File ".../venv/lib/python3.9/site-packages/pyalgotrade/technical/__init__.py", line 88, in __onNewValue
    self.__eventWindow.onNewValue(dateTime, value)
  File ".../venv/lib/python3.9/site-packages/pyalgotrade/technical/rsi.py", line 83, in onNewValue
    super(RSIEventWindow, self).onNewValue(dateTime, value)
  File ".../venv/lib/python3.9/site-packages/pyalgotrade/technical/__init__.py", line 48, in onNewValue
    self.__values.append(value)
  File ".../venv/lib/python3.9/site-packages/pyalgotrade/utils/collections.py", line 73, in append
    self.__values[self.__nextPos] = value
TypeError: float() argument must be a string or a number, not 'BasicBar'

**Comment by matanume** [comment]
Sorry, my false forget to add getDataSeries()
