### ISSUE TITLE
bitstamp example not working

### ISSUE THREAD

**Issue by geoffwalmsley** [gbeced/pyalgotrade#63]
Following setup, running the bitstamp example from the docs generates a 502 bad gateway error, then using ctrl-c to bail out just leaves me with a hung terminal. 

I'm using python within a virtualenv, on macosx 10. 

Output dump:

2015-12-28 15:52:52,140 bitstamp [INFO] Initializing websocket client.
2015-12-28 15:52:53,311 tornado.application [ERROR] Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/Users/apollo/Venv/BC/lib/python2.7/site-packages/tornado/iostream.py", line 554, in wrapper
    return callback(*args)
  File "/Users/apollo/Venv/BC/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/apollo/Venv/BC/lib/python2.7/site-packages/ws4py/client/tornadoclient.py", line 84, in __handshake_completed
    self.process_response_line(response_line)
  File "/Users/apollo/Venv/BC/lib/python2.7/site-packages/ws4py/client/__init__.py", line 284, in process_response_line
    raise HandshakeError("Invalid response status: %s %s" % (code, status))
HandshakeError: Invalid response status: 502 Bad Gateway
2015-12-28 15:52:53,312 tornado.application [ERROR] Exception in callback <functools.partial object at 0x10453eb50>
Traceback (most recent call last):
  File "/Users/apollo/Venv/BC/lib/python2.7/site-packages/tornado/ioloop.py", line 600, in _run_callback
    ret = callback()
  File "/Users/apollo/Venv/BC/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/apollo/Venv/BC/lib/python2.7/site-packages/tornado/iostream.py", line 554, in wrapper
    return callback(*args)
  File "/Users/apollo/Venv/BC/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/apollo/Venv/BC/lib/python2.7/site-packages/ws4py/client/tornadoclient.py", line 84, in __handshake_completed
    self.process_response_line(response_line)
  File "/Users/apollo/Venv/BC/lib/python2.7/site-packages/ws4py/client/__init__.py", line 284, in process_response_line
    raise HandshakeError("Invalid response status: %s %s" % (code, status))
HandshakeError: Invalid response status: 502 Bad Gateway
^C2015-12-28 15:52:58,720 bitstamp [INFO] Shutting down websocket client.
^C

**Comment by geoffwalmsley** [comment]
I also tried running the code in the bitstamp tutorial and get an error on line 1:

from pyalgotrade.bitstamp import client

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name client

**Comment by gbeced** [comment]
Which version of PyAlgoTrade are you using ? Please send me a complete example that reproduces the error.

**Comment by gbeced** [comment]
I just tried this and its working ok. Please reopen with proper steps to reproduce.

**Comment by bleechack** [comment]
I got this too, but figured it out.

Turns out when you use the v0.15 example with the v0.18 PyAlgoTrade, you get this error.

Just an FYI...
