### ISSUE TITLE
Tutorial: download orcl-2000.csv fail, HTTP url not found

### ISSUE THREAD

**Issue by RavenUP** [gbeced/pyalgotrade#99]
I execute this command:
`$ python -c "from pyalgotrade.tools import yahoofinance; yahoofinance.download_daily_bars('orcl', 2000, 'orcl-2000.csv')"
`
And receive error:

> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pyalgotrade/tools/yahoofinance.py", line 54, in download_daily_bars
    bars = download_csv(instrument, datetime.date(year, 1, 1), datetime.date(year, 12, 31), "d")
  File "/usr/local/lib/python2.7/site-packages/pyalgotrade/tools/yahoofinance.py", line 40, in download_csv
    return csvutils.download_csv(url)
  File "/usr/local/lib/python2.7/site-packages/pyalgotrade/utils/csvutils.py", line 59, in download_csv
    response.raise_for_status()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 929, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ichart.finance.yahoo.com/table.csv?s=orcl&a=0&b=1&c=2000&d=11&e=31&f=2000&g=d&ignore=.csv

How's that going?

**Comment by RavenUP** [comment]
The tutorial is:
http://gbeced.github.io/pyalgotrade/docs/v0.18/html/tutorial.html

**Comment by njgraham** [comment]
Same here - perhaps Yahoo doesn't support that URL anymore.  `nslookup` for `ichart.finance.yahoo.com` fails.

**Comment by gbeced** [comment]
Yahoo Finance API is broken for a while and I will remove support for it, but I'd also like to re-write the tutorial using a different source.
Google Finance doesn't seem to have adjusted prices.
Any idea of what would be a good data source for historical prices that includes adjusted values ?
Thanks

**Comment by gbeced** [comment]
I'll follow up on https://github.com/gbeced/pyalgotrade/issues/98

**Comment by vadimk2016** [comment]
Also does not work with google finance.
```
~: python -c "from pyalgotrade.tools import googlefinance; googlefinance.download_daily_bars('orcl', 2000, 'orcl-2000.csv')"
http://www.google.com/finance/historical?q=orcl&startdate=Jan+01,+2000&enddate=Dec+31,+2000&output=csv
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pyalgotrade/tools/googlefinance.py", line 65, in download_daily_bars
    datetime.date(year, 12, 31))
  File "pyalgotrade/tools/googlefinance.py", line 40, in download_csv
    f = urllib2.urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

**Comment by vadimk2016** [comment]
Also does not work with google finance.
```
~: python -c "from pyalgotrade.tools import googlefinance; googlefinance.download_daily_bars('orcl', 2000, 'orcl-2000.csv')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pyalgotrade/tools/googlefinance.py", line 65, in download_daily_bars
    datetime.date(year, 12, 31))
  File "pyalgotrade/tools/googlefinance.py", line 40, in download_csv
    f = urllib2.urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

**Comment by gbeced** [comment]
@vadimk2016 Support for downloading bars via Google Finance was removed on https://github.com/gbeced/pyalgotrade/commit/784fc8024e0188b8d2f6c3827960d41fc5a26efb
